Httpi\Bundle\CoreBundle\Entity\Status:
  type: entity
  table: status
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50